# Generated by Django 4.0.4 on 2022-04-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='formulario',
            new_name='register',
        ),
    ]
