# Generated by Django 4.0.3 on 2022-04-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='articulos',
            new_name='articulo',
        ),
        migrations.RenameModel(
            old_name='clientes',
            new_name='cliente',
        ),
        migrations.RenameModel(
            old_name='pedidos',
            new_name='pedido',
        ),
    ]
