# Generated by Django 4.0.3 on 2022-04-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0002_rename_articulos_articulo_rename_clientes_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField()),
                ('apellido', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
