# Generated by Django 4.0.3 on 2022-04-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0003_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
