# Generated by Django 4.0.3 on 2022-04-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0003_articles_contact'),
        ('ProyectoWebApp', '0004_alter_registro_apellido_alter_registro_nombre'),
    ]

    operations = [
    ]
